version: '3.9'

services:
  db:
    image: docker.io/postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: test1234
      POSTGRES_USER: admin
      POSTGRES_DB: ddt
  adminer:
    image: docker.io/adminer
    restart: always
    ports:
      - 9080:8080
